-- Schema export generated by app:export-schema
-- For a 100% exact 'Golden Template' (with complex triggers, indices, etc.), running `pg_dump --schema-only` is recommended.

-- ---------------------------------------------------------
-- Table structure for `settings`
-- ---------------------------------------------------------

CREATE TABLE "settings" (
    "id" bigint DEFAULT nextval('settings_id_seq'::regclass) NOT NULL,
    "key" character varying(255) NOT NULL,
    "value" text,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `orders`
-- ---------------------------------------------------------

CREATE TABLE "orders" (
    "id" bigint DEFAULT nextval('orders_id_seq'::regclass) NOT NULL,
    "order_id" character varying(255) NOT NULL,
    "customer_name" character varying(255) NOT NULL,
    "customer_email" character varying(255) NOT NULL,
    "phone" character varying(255) NOT NULL,
    "company_name" character varying(255),
    "website_url" character varying(255),
    "plan" character varying(255) NOT NULL,
    "strategy" character varying(255) NOT NULL,
    "distribution_reach" integer NOT NULL,
    "total_amount" numeric NOT NULL,
    "status" character varying(255) DEFAULT 'Pending'::character varying NOT NULL,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "brand_id" bigint,
    "current_step" integer DEFAULT 1 NOT NULL,
    "staff_id" bigint,
    "is_payment_verified" boolean DEFAULT false,
    "is_content_verified" boolean DEFAULT false,
    "approved_at" timestamp without time zone,
    "completed_at" timestamp without time zone,
    "receipt_path" character varying(255),
    "rejection_reason" text,
    "report_file" character varying(255),
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `brands`
-- ---------------------------------------------------------

CREATE TABLE "brands" (
    "id" integer DEFAULT nextval('brands_id_seq'::regclass) NOT NULL,
    "name" character varying(255) NOT NULL,
    "logo" character varying(255),
    "primary_color" character varying(255) DEFAULT '#FF2D46'::character varying,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `offline_payments`
-- ---------------------------------------------------------

CREATE TABLE "offline_payments" (
    "id" bigint DEFAULT nextval('offline_payments_id_seq'::regclass) NOT NULL,
    "offline_client_id" bigint NOT NULL,
    "period_month" smallint NOT NULL,
    "period_year" smallint NOT NULL,
    "amount" numeric NOT NULL,
    "paid_at" timestamp without time zone NOT NULL,
    "marked_by" bigint,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "notes" text,
    "invoice_number" character varying(30),
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `offline_clients`
-- ---------------------------------------------------------

CREATE TABLE "offline_clients" (
    "id" bigint DEFAULT nextval('offline_clients_id_seq'::regclass) NOT NULL,
    "company_name" character varying(255) NOT NULL,
    "pic_name" character varying(255) NOT NULL,
    "pic_phone" character varying(255) NOT NULL,
    "pic_email" character varying(255),
    "total_package" numeric,
    "monthly_payment" numeric NOT NULL,
    "contract_start" date NOT NULL,
    "due_day" smallint DEFAULT '1'::smallint NOT NULL,
    "notes" text,
    "status" character varying(20) DEFAULT 'active'::character varying NOT NULL,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "billing_mode" character varying(20) DEFAULT 'fixed'::character varying NOT NULL,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `users`
-- ---------------------------------------------------------

CREATE TABLE "users" (
    "id" bigint DEFAULT nextval('users_id_seq'::regclass) NOT NULL,
    "name" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "email_verified_at" timestamp without time zone,
    "password" character varying(255) NOT NULL,
    "remember_token" character varying(100),
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "role" character varying(255) DEFAULT 'staff'::character varying NOT NULL,
    "is_super_admin" boolean DEFAULT false,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `migrations`
-- ---------------------------------------------------------

CREATE TABLE "migrations" (
    "id" integer DEFAULT nextval('migrations_id_seq'::regclass) NOT NULL,
    "migration" character varying(255) NOT NULL,
    "batch" integer NOT NULL,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `password_reset_tokens`
-- ---------------------------------------------------------

CREATE TABLE "password_reset_tokens" (
    "email" character varying(255) NOT NULL,
    "token" character varying(255) NOT NULL,
    "created_at" timestamp without time zone,
    PRIMARY KEY ("email")
);

-- ---------------------------------------------------------
-- Table structure for `failed_jobs`
-- ---------------------------------------------------------

CREATE TABLE "failed_jobs" (
    "id" bigint DEFAULT nextval('failed_jobs_id_seq'::regclass) NOT NULL,
    "uuid" character varying(255) NOT NULL,
    "connection" text NOT NULL,
    "queue" text NOT NULL,
    "payload" text NOT NULL,
    "exception" text NOT NULL,
    "failed_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `personal_access_tokens`
-- ---------------------------------------------------------

CREATE TABLE "personal_access_tokens" (
    "id" bigint DEFAULT nextval('personal_access_tokens_id_seq'::regclass) NOT NULL,
    "tokenable_type" character varying(255) NOT NULL,
    "tokenable_id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "token" character varying(64) NOT NULL,
    "abilities" text,
    "last_used_at" timestamp without time zone,
    "expires_at" timestamp without time zone,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `order_logs`
-- ---------------------------------------------------------

CREATE TABLE "order_logs" (
    "id" bigint DEFAULT nextval('order_logs_id_seq'::regclass) NOT NULL,
    "order_id" bigint NOT NULL,
    "user" character varying(255) DEFAULT 'System'::character varying NOT NULL,
    "action" character varying(255) NOT NULL,
    "details" text,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    PRIMARY KEY ("id")
);

-- ---------------------------------------------------------
-- Table structure for `customers`
-- ---------------------------------------------------------

CREATE TABLE "customers" (
    "id" bigint DEFAULT nextval('customers_id_seq'::regclass) NOT NULL,
    "name" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "phone" character varying(255),
    "total_spent" numeric DEFAULT '0'::numeric NOT NULL,
    "order_count" integer DEFAULT 0 NOT NULL,
    "is_vip" boolean DEFAULT false NOT NULL,
    "last_order_at" timestamp without time zone,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    PRIMARY KEY ("id")
);
